# Generated by Django 4.1.4 on 2023-03-02 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='teams_obj', to='tournament.event'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.event', verbose_name='event_obj'),
        ),
    ]
