# Generated by Django 4.1.4 on 2023-03-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_team_teams_alter_announcement_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='teams',
        ),
        migrations.AddField(
            model_name='team',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='events_obj', to='tournament.event'),
        ),
    ]
