# Generated by Django 4.1.4 on 2023-03-04 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_remove_team_teams_team_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='name',
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players_obj', to='tournament.team'),
        ),
    ]
